In [1]:
import pandas as pd
import os
import numpy as num

In [7]:
reviews = pd.read_csv(r'F:/Study/Marketing Analytics/Datasets/amazon-reviews.csv')
reviews.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
0,0,NaN,4.0,No issues.,2014-07-23,138,0,0,0,0,0.0,0.0
1,1,0mie,5.0,"Purchased this for my device, it worked as adv...",2013-10-25,409,0,0,0,0,0.0,0.0
2,2,1K3,4.0,it works as expected. I should have sprung for...,2012-12-23,715,0,0,0,0,0.0,0.0
3,3,1m2,5.0,This think has worked out great.Had a diff. br...,2013-11-21,382,0,0,0,0,0.0,0.0
4,4,2&amp;1/2Men,5.0,"Bought it with Retail Packaging, arrived legit...",2013-07-13,513,0,0,0,0,0.0,0.0

In [10]:
review = reviews[['reviewText']]
review.head()

                                          reviewText
0                                         No issues.
1  Purchased this for my device, it worked as adv...
2  it works as expected. I should have sprung for...
3  This think has worked out great.Had a diff. br...
4  Bought it with Retail Packaging, arrived legit...

Data Processing


*Convert only in lower case *Remove stop words - is the a *Remove punchuations

Lower case

In [11]:
review['lower case'] = review['reviewText'].str.lower()

C:\Users\hp\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
review['clean text'] = review['lower case'].str.replace("[^a-z\'']"," ")
review.head()

C:\Users\hp\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,reviewText,lower case,clean text
0,No issues.,no issues.,no issues
1,"Purchased this for my device, it worked as adv...","purchased this for my device, it worked as adv...",purchased this for my device it worked as adv...
2,it works as expected. I should have sprung for...,it works as expected. i should have sprung for...,it works as expected i should have sprung for...
3,This think has worked out great.Had a diff. br...,this think has worked out great.had a diff. br...,this think has worked out great had a diff br...
4,"Bought it with Retail Packaging, arrived legit...","bought it with retail packaging, arrived legit...",bought it with retail packaging arrived legit...

In [13]:
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
stop_words = stopwords.words('english')

Creating function for removing all stop words

In [22]:
def sw(x):
    x = [word_list for word_list in str(x).split() if word_list not in stop_words]
    return " ".join(x)

In [24]:
review['final text'] = review['clean text'].apply(sw)
review.head()

C:\Users\hp\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,reviewText,lower case,clean text,final text
0,No issues.,no issues.,no issues,issues
1,"Purchased this for my device, it worked as adv...","purchased this for my device, it worked as adv...",purchased this for my device it worked as adv...,purchased device worked advertised never much ...
2,it works as expected. I should have sprung for...,it works as expected. i should have sprung for...,it works as expected i should have sprung for...,works expected sprung higher capacity think ma...
3,This think has worked out great.Had a diff. br...,this think has worked out great.had a diff. br...,this think has worked out great had a diff br...,think worked great diff bran gb card went sout...
4,"Bought it with Retail Packaging, arrived legit...","bought it with retail packaging, arrived legit...",bought it with retail packaging arrived legit...,bought retail packaging arrived legit orange e...

Creating DTM

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
count_vec=CountVectorizer()
count_vec.fit(review['final text'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [29]:
DTM = count_vec.fit_transform(review['final text'])
DTM

<4915x7510 sparse matrix of type '<class 'numpy.int64'>'
	with 107990 stored elements in Compressed Sparse Row format>

In [30]:
DTM_df = pd.DataFrame(DTM.toarray(), columns = count_vec.get_feature_names())
DTM_df

,aaaaaaaa,aac,aacute,aas,abdroid,abilities,ability,able,aboutthere,aboutto,...,zips,zl,zone,zoning,zoom,zte,ztpad,zumo,zune,zunehd
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4910,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4911,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4912,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4913,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4914,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
frequent = DTM_df.sum().reset_index()
frequent.sort_values(by = 0,ascending=False).head(20)

        index     0
905      card  4721
4709    phone  1782
2662       gb  1771
7394    works  1586
2811    great  1481
3953   memory  1374
5664  sandisk  1339
5742       sd  1248
7059      use  1125
4410      one  1103
2639   galaxy  1026
913     cards   938
2327     fast   924
2762     good   904
4948    price   872
5655  samsung   842
707    bought   838
6328  storage   781
7408    would   702
7281     well   694

## Customer Sentiment Anlaysis

In [32]:
!pip install vaderSentiment
import vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sentiment = SentimentIntensityAnalyzer()

Requirement already satisfied: vaderSentiment in c:\users\hp\conda\lib\site-packages (3.3.2)
Requirement already satisfied: requests in c:\users\hp\conda\lib\site-packages (from vaderSentiment) (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\hp\conda\lib\site-packages (from requests->vaderSentiment) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\hp\conda\lib\site-packages (from requests->vaderSentiment) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\conda\lib\site-packages (from requests->vaderSentiment) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\hp\conda\lib\site-packages (from requests->vaderSentiment) (3.0.4)

In [33]:
review_final = review[['reviewText']]
review_final

                                             reviewText
0                                            No issues.
1     Purchased this for my device, it worked as adv...
2     it works as expected. I should have sprung for...
3     This think has worked out great.Had a diff. br...
4     Bought it with Retail Packaging, arrived legit...
...                                                 ...
4910  I bought this Sandisk 16GB Class 10 to use wit...
4911  Used this for extending the capabilities of my...
4912  Great card that is very fast and reliable. It ...
4913  Good amount of space for the stuff I want to d...
4914  I've heard bad things about this 64gb Micro SD...

[4915 rows x 1 columns]

In [38]:
review_final['Compound score'] = [sentiment.polarity_scores(str(x))['compound'] for x in review_final['reviewText']]
review_final

C:\Users\hp\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                                             reviewText  Compound score
0                                            No issues.         -0.2960
1     Purchased this for my device, it worked as adv...         -0.2960
2     it works as expected. I should have sprung for...         -0.3089
3     This think has worked out great.Had a diff. br...          0.7081
4     Bought it with Retail Packaging, arrived legit...          0.7087
...                                                 ...             ...
4910  I bought this Sandisk 16GB Class 10 to use wit...          0.0018
4911  Used this for extending the capabilities of my...          0.1761
4912  Great card that is very fast and reliable. It ...          0.8588
4913  Good amount of space for the stuff I want to d...          0.4939
4914  I've heard bad things about this 64gb Micro SD...          0.8923

[4915 rows x 2 columns]

In [39]:
review_final['Compound score'].mean()

0.48144590030518697

In [40]:
review_final['Category'] = pd.cut(review_final['Compound score'],
                             bins=[-1,-0.5,0.5,1],
                             labels=['negative','neutral','positive',])

C:\Users\hp\conda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [41]:
review_final.groupby('Category').size()

Category
negative     264
neutral     1636
positive    3015
dtype: int64

In [43]:
review_final['Category'].value_counts(normalize=True)

positive    0.613428
neutral     0.332859
negative    0.053713
Name: Category, dtype: float64